app:
  env: "local"
  port: "8000"
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
urls:
  balance: "https://www.zgtest.club/api/v2/user/balance"
  config: "https://www.zexchange.xyz/api/wallet/v1/currency/config"