# db:
#db_user:用户名
#ip:db_home
#db_name:数据库名
#mysql密码:db_pass
#最大闲置数量:max_conn
#最大连接:max_open
# redis:
#ip_port:ip及端口
#password:密码
localhost:
  #db:
    db_user: root
    db_home: 127.0.0.1
    db_name: yoawo
    db_pass: root
    max_conn: 5
    max_open: 5
  #redis:
    ip_port: 127.0.0.1:6379
    password: ""
test35:
  #db:
    db_user: root
    db_home: 127.0.0.1
    db_name: yoawo
    db_pass: 123456
    max_conn: 5
    max_open: 5
  #redis:
    ip_port: 127.0.0.1:6379
    password: 123456
product:
  #db:
    db_user: "server"
    db_home: "rm-2ze0vj2espbt2nfj7.mysql.rds.aliyuncs.com"
    db_name: "dbtest"
    db_pass: "b!Ac@e#e$a%R^57&Q*C(DF)F_A+S=E"
    max_conn: 5
    max_open: 5
  #redis:
    ip_port: "r-2ze2efb1366d8574.redis.rds.aliyuncs.com:6379"
    password: "ab@1da4D$%^&*an*!a"