# db:
#db_user:用户名
#ip:db_home
#db_name:数据库名
#mysql密码:db_pass
#最大闲置数量:max_conn
#最大连接:max_open
# redis:
#ip_port:ip及端口
#password:密码
localhost:
  #db:
    db_user: root
    db_home: 127.0.0.1
    db_name: yoawo
    db_pass: root
    max_conn: 5
    max_open: 5